### ISSUE TITLE
Create "Business Formations" indicator page

### ISSUE THREAD

**Issue by bgruswitz** [dvrpc/TrackingProgress#101]
This new page can replace "Innovation", which we're discontinuing.

Four tabs of text can be just the "tbd" found currently in these files: G:\Shared drives\Socioeconomic and Land Use Analytics\Tracking Progress\Web\Data\_text\Business Formations

One chart is required

- data source: G:\Shared drives\Socioeconomic and Land Use Analytics\Tracking Progress\Web\Data\Business Formations\business_formations.csv
- chart type: line
- chart title: Business Formations
- legend will be geographies with DVRPC Region on as default and will be indicated in data by the first text in the field name.
![image](https://user-images.githubusercontent.com/27835348/212405418-d12d47d1-925e-43c3-9b55-56291a4de213.png)
- text under chart saying what asterisks mean is required, "Geography: * Regional, ** County"
- Source line under chart will read, "Source: U.S. Census Bureau's Business Formation Statistics"
- Single dropdown, with "Select Value Type" preceding it, is required with the following selections:
    - "Total" from all columns ending in "_total" 
        - Y axis label: "Total Business Formations"
        - data value format (Y axis and tooltip): x,xxx
    - "Change Since Base Year" from all columns ending in "_cumu_chng"         
        - Y axis label: "Total Business Formations"
        - data value format (Y axis and tooltip): x,xxx
    - "Percent Change Since Base Year" from all columns ending in "_cumu_perc_chng" 
        - Y axis label: "Total Business Formations"
        - data value format (Y axis and tooltip): xx.x%
- X axis label: "Year"

**Comment by hachadorian** [comment]
@bgruswitz I started the business formations page and updated the staging site. fyi in the csv "burlington" is spelled "burlingon" im not sure if that's intentional but just letting you know
