### ISSUE TITLE
tooltip fix for decimals to display as percent

### ISSUE THREAD

**Issue by bgruswitz** [dvrpc/TrackingProgress#74]
@mmolta I'm not sure if you investigated this suggested fix I sent you yet. Just want to make sure it was attempted and that we log it as an ongoing issue. A contact in Missouri sent the following suggestion: 

> Ben, I suspect you are just setting tooltips to "true" in your program. You will need a custom tooltip. The "contentGenerator" is used for that. I have attached a sample pic that  I generated with the code below. You can see that the tooltip shows percent instead of decimals. I think it should work for the emissions figure. If you are unable to fix it, just send me the code you are using, and I will try and fix it.  
> 
![image](https://user-images.githubusercontent.com/27835348/173164997-bd79c2fc-4ac7-4e03-ab5b-d58e63a2742a.png)

<img width="747" alt="Screen Shot 2020-06-29 at 1 45 32 PM" src="https://user-images.githubusercontent.com/27835348/173165020-022fd2b7-6a8d-4049-b48b-ba9dfc97f602.png">

**Comment by hachadorian** [comment]
@bgruswitz im not going to add this to staging since it would get rid of the business formations updates but here is a screenshot of the fix:
![Screenshot 2023-01-17 153728](https://user-images.githubusercontent.com/49740237/213007290-064fd91c-1d74-4acd-8072-108ce5b4773b.png)

**Comment by bgruswitz** [comment]
@hachadorian fantastic! That's what we're looking for. So you're needing to push the business formations updates to staging first, and then you can add this?

**Comment by hachadorian** [comment]
@bgruswitz I made two different branches for the tooltip and Business formations update but I could add both changes to staging just have to merge one branch in the other locally then update staging. I can do that tomorrow that way can see if the tooltip looks like it should on all the other charts. I'll let you know when I update staging

**Comment by hachadorian** [comment]
@bgruswitz just updated staging

**Comment by bgruswitz** [comment]
@hachadorian this is so cool to see working! Just noticing on greenhouse gas emissions that chart 3: "Electricity Generation Mix by Source" is looking way better, but the preceding chart 2: "Greenhouse Gas Emissions by Source" looks like everything's displaying as percents, even though it should just be xx.x. Not sure if this is happening elsewhere.
