### ISSUE TITLE
Continued trendlines through null value years

### ISSUE THREAD

**Issue by bgruswitz** [dvrpc/TrackingProgress#78]
It's already been somewhat an issue, but we're going to have an increase in skipped years with data that didn't get released for 2020 due to the pandemic. We could really use a fix that allows trend lines to connect a line directly from 2019 to 2021, for example, when 2020 has a null value. Otherwise 2021 will look empty as well. We may wish to put markers on each line vertex for each year we have a values so that skipped years look like there was nothing to report.

I'm tagging folks just so we're all aware of the issue: @mmolta @hachadorian @jstrangfeld @ISchwarzenbergDVRPC @BrettFusco

**Comment by bgruswitz** [comment]
@hachadorian this issue needs addressing before we can make this larger batch update. The new Commute Mode data doesn't exist for 2020 because of disruptions to the survey that collects it during the pandemic. Commuting still happened, but it looks like it went down to zero in the charts now. If every year that has a data value has a small marker point along the line, and then anything with a null value would have a line, but no marker and connect directly from the last marker to the most recent marker over the null year(s).

**Comment by bgruswitz** [comment]
@hachadorian this is definitely better, but I still would like to see small marker dots along the lines where a value is present.

**Comment by hachadorian** [comment]
![Screenshot 2023-01-19 082913](https://user-images.githubusercontent.com/49740237/213455056-cf1f23ed-0dcb-4dea-995b-0ffa467c815b.png)
@bgruswitz something like this?

**Comment by bgruswitz** [comment]
@hachadorian yep! That's what I'm looking for. Nice!
