### ISSUE TITLE
Support markdown files for indicator text

### ISSUE THREAD

**Issue by hachadorian** [dvrpc/TrackingProgress#86]
Refactor MIT links be sure not to remove links unrelated to MIT

**Comment by bgruswitz** [comment]
@hachadorian do you think that we should just rename this issue "Use markdown files for indicator page text" or something? Doing that task will resolve the links issue.

**Comment by bgruswitz** [comment]
@hachadorian The text looks like it's all set. Just need to resolve this (#90) before pushing to production.

**Comment by bgruswitz** [comment]
@hachadorian 

Good to close on my end, but I think you may have had a reason to keep it open.
