### ISSUE TITLE
Graph's not displaying properly on 3 pages

### ISSUE THREAD

**Issue by bgruswitz** [dvrpc/TrackingProgress#90]
@hachadorian it appears as if the three pages with modifications last summer have issues with their charts. They are Commute Mode, Job Growth, and Racial & Ethnic Disparities. We'll need this resolved prior to pushing staging to production.

**Comment by hachadorian** [comment]
@bgruswitz Ben these should be fixed now if everything looks good on staging maybe we can push the text updates

**Comment by bgruswitz** [comment]
@hachadorian looks great. Go ahead and make the push and close this and the markdown issue. Thanks!
