### ISSUE TITLE
signal for new updates on dashboard works

### ISSUE THREAD

**Issue by bgruswitz** [dvrpc/TrackingProgress#91]
@hachadorian Ensure code that will signals new updates on dashboard tiles is in staging version. Let me know if any icon or CS work from Becky is needed, or if you have what you need.

**Comment by bgruswitz** [comment]
@hachadorian I believe [this repo](https://github.com/dvrpc/tp-updates) is relevant to this issue. @mmolta and @kdwarn can confirm.

**Comment by kdwarn** [comment]
Yep, that's the repo with the API for adding the "updated" label to tiles; it also has info on the front end for it.

**Comment by hachadorian** [comment]
@kdwarn thanks kris, i think the only thing to fix here is updating the endpoint. Right now its using "http://linux2.dvrpc.org/tracking-progress/v1/indicators" when it should be using "http://linux3.dvrpc.org/api/tp-updates/v1/indicators"

right here: https://github.com/dvrpc/TrackingProgress/blob/master/js/index.js#L277

**Comment by hachadorian** [comment]
@kdwarn would you be able to create a couple of test "updates"?
