### ISSUE TITLE
Move enhancements for Racial and Ethnic Disparities back to staging

### ISSUE THREAD

**Issue by bgruswitz** [dvrpc/TrackingProgress#94]
@hachadorian Let me know when this moves back I'll check for any errors.

**Comment by hachadorian** [comment]
@bgruswitz ben im nearly finished with returning the data updates however if you look at the object here for the labForByRace_gap chart https://github.com/dvrpc/TrackingProgress/blob/master/js/ref.js#L1215 and look at the property columnOptions, these options are much different than the chart that is in the shared drive https://docs.google.com/spreadsheets/d/1kVOlyd8RG6elesGRMsUIfvGQCv4Xry-E56GaZ08jGuM/edit#gid=1374283372

**Comment by bgruswitz** [comment]
@hachadorian 

All looks good. Thanks! Okay, on my end, to close.
