### ISSUE TITLE
Update front end with new data for Bridge Conditions

### ISSUE THREAD

**Issue by bgruswitz** [dvrpc/TrackingProgress#96]
@hachadorian G:\Shared drives\Socioeconomic and Land Use Analytics\Tracking Progress\Web\Data\Bridge Conditions

**Comment by bgruswitz** [comment]
@hachadorian this is all set now. @DVRPCfreight fixed the headers.

**Comment by hachadorian** [comment]
@bgruswitz just added the updated data to staging
