### ISSUE TITLE
Update front end with new data for Housing Activity

### ISSUE THREAD

**Issue by bgruswitz** [dvrpc/TrackingProgress#97]
@hachadorian G:\Shared drives\Socioeconomic and Land Use Analytics\Tracking Progress\Web\Data\Housing Activity

**Comment by bgruswitz** [comment]
@hachadorian this is all set now. @DVRPCfreight fixed the headers.

**Comment by hachadorian** [comment]
@bgruswitz just added the updated data to staging

**Comment by bgruswitz** [comment]
@hachadorian after a fix from @DVRPCfreight, this is ready to re-upload.

**Comment by hachadorian** [comment]
@bgruswitz just replaced the files

**Comment by hachadorian** [comment]
@bgruswitz Im gonna close this issue #95 and #96 since theres no code that actually addresses these changes
