### ISSUE TITLE
3 indicator page reconfigurations

### ISSUE THREAD

**Issue by bgruswitz** [dvrpc/TrackingProgress#99]
@hachadorian 

To reconfiguring the 3 indicator pages I suggest:

- "Income Disparities" becomes "Income"
- "Racial and Ethnic Disparities" becomes "Segregation"
- "Sex Disparities" becomes "Labor Force"

Here's the new pages and location of their charts on the current pages. There's a chance I will do some renaming, but would like to see them in their new homes first. Also, Income now will break the record for having 6 charts. This makes me want to do that consolidation of Gaps and Totals in a double toggle that I mentioned, so they could reduce to 3 charts. But I'll put that in as a separate issue with medium priority.

Current Page | Chart Number | Chart Name | New Page | New Number
-- | -- | -- | -- | --
Income Disparities | 1 | Income Growth Gap between Highest Quintile & Lowest Quintile Households | Income | 1
Income Disparities | 2 | Average Income by Household Income Grouping | Income | 2
Racial and Ethnic Disparities | 1 | Median Income Gap Relative to Households with White, non-Latinx Householder | Income | 3
Racial and Ethnic Disparities | 2 | Median Household Income by Householder’s Major Race or Ethnic Group | Income | 4
Sex Disparities | 1 | Median Income Gap between Sexes | Income | 5
Sex Disparities | 2 | Median Income by Sex | Income | 6
Sex Disparities | 3 | Labor Force Participation Gap between Sexes | Labor Force | 1
Sex Disparities | 4 | Labor Force Participation by Sex | Labor Force | 2
Racial and Ethnic Disparities | 4 | Labor Force Participation Gap Relative to White Participation Rate | Labor Force | 3
Racial and Ethnic Disparities | 5 | Labor Force Participation by Race | Labor Force | 4
Racial and Ethnic Disparities | 3 | Racial/Ethnic Segregation Index | Segregation | 1
Income Disparities | 3 | Income Segregation Index | Segregation | 2

**Comment by hachadorian** [comment]
@bgruswitz staging is updated with these changes

**Comment by hachadorian** [comment]
@bgruswitz do these as well as #101 look good? @mmolta is going to start updating the UI soon.

**Comment by bgruswitz** [comment]
Hey @hachadorian. Looking good--awesome, in fact--but noticed the on Income: 2nd to last chart -- no change when selecting Percent Gap in the second drop-down menu.

**Comment by hachadorian** [comment]
@bgruswitz should be working now

**Comment by bgruswitz** [comment]
@hachadorian looks good on my end. You can close this one. Soon, but later, we'll supply some new data to feed the charts. And #100 deals with an ideal consolidation of charts if possible, but is dealt with separately.
